######### This code applies singleseqgset analysis to investigate enriched and depleted GO terms between adult and neo P14 eos from the CO and SI ##########
# Figure 3

##### Set up environment 
setwd("/home/khandl")

##### link to libraries and functions
source("~/Projects/Neonatal_eosinophils/1.1.Packages.R")
source("~/Projects/Neonatal_eosinophils/1.7.Functions_GSEA_PROGENy_SCENIC.R")

### load seurat objects 
obj <- readRDS("/data/khandl/Neonatal_eosinophils/seurat_objects/Neo_P14_adult_eos_CO_SI_LT.rds")

## extract only CO and SI 
Idents(obj) <- "condition"
obj <- subset(obj, idents = c("adult_colon","adult_small_int","NEO_P14_colon","NEO_P14_small_int"))

##### load gene sets 
### KEGG
kegg <- msigdbr(species="Mus musculus",category="C2",subcategory = "KEGG")

kegg.names <- unique(kegg$gs_name)

kegg.sets <- vector("list",length=length(kegg.names))
names(kegg.sets) <- kegg.names

for (i in names(kegg.sets)) {
  kegg.sets[[i]] <- pull(kegg[kegg$gs_name==i,"gene_symbol"])
}

### BP
bp <- msigdbr(species="Mus musculus",category="C5",subcategory = "BP")

bp.names <- unique(bp$gs_name)

bp.sets <- vector("list",length=length(bp.names))
names(bp.sets) <- bp.names

for (i in names(bp.sets)) {
  bp.sets[[i]] <- pull(bp[bp$gs_name==i,"gene_symbol"])
}

### Reactome 
R <- msigdbr(species="Mus musculus",category="C2",subcategory = "REACTOME")

R.names <- unique(R$gs_name)

R.sets <- vector("list",length=length(R.names))
names(R.sets) <- R.names

for (i in names(R.sets)) {
  R.sets[[i]] <- pull(R[R$gs_name==i,"gene_symbol"])
}

### Hallmarks 
H <- msigdbr(species="Mus musculus",category="H")

H.names <- unique(H$gs_name)

H.sets <- vector("list",length=length(H.names))
names(H.sets) <- H.names

for (i in names(H.sets)) {
  H.sets[[i]] <- pull(H[H$gs_name==i,"gene_symbol"])
}

all_sets <- c(H.sets, R.sets, bp.sets, kegg.sets)

##### run singleseqset 
singleseqset_to_csv(obj,"condition","bonferroni", "/scratch/khandl/Neonatal_eosinophils/data_files/singleseqgset/singleseqgset_CO_SI_adult_and_neoP14_bonf.csv") 

##### plot GO terms of interest 
### Effector functions 
## all clusters combined 
go_terms <- read.csv("/scratch/khandl/Neonatal_eosinophils/data_files/singleseqgset/singleseqgset_CO_SI_adult_and_neoP14_bonf.csv")

terms_oi <- c(#21 - Regulation of non-immune cell
  "GOBP_REGULATION_OF_ENDOTHELIAL_CELL_MIGRATION",
  "GOBP_POSITIVE_REGULATION_OF_ENDOTHELIAL_CELL_MIGRATION",
  "GOBP_POSITIVE_REGULATION_OF_EPITHELIAL_CELL_PROLIFERATION",
  "GOBP_REGULATION_OF_EPITHELIAL_CELL_MIGRATION",
  "GOBP_POSITIVE_REGULATION_OF_EPITHELIAL_CELL_MIGRATION",
  "GOBP_NEGATIVE_REGULATION_OF_EPITHELIAL_CELL_PROLIFERATION",
  "GOBP_GLOMERULAR_EPITHELIAL_CELL_DIFFERENTIATION",
  "GOBP_EPITHELIAL_CELL_DEVELOPMENT",
  "GOBP_MESENCHYMAL_CELL_DIFFERENTIATION",
  "GOBP_COLLAGEN_ACTIVATED_SIGNALING_PATHWAY",
  "GOBP_GLOMERULAR_EPITHELIUM_DEVELOPMENT",
  "GOBP_MESENCHYME_MORPHOGENESIS",
  "GOBP_MORPHOGENESIS_OF_AN_EPITHELIUM",
  "GOBP_POSITIVE_REGULATION_OF_FIBROBLAST_MIGRATION",
  "GOBP_POLARIZED_EPITHELIAL_CELL_DIFFERENTIATION",
  "GOBP_ESTABLISHMENT_OF_EPITHELIAL_CELL_APICAL_BASAL_POLARITY",
  "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION",
  "GOBP_ESTABLISHMENT_OF_EPITHELIAL_CELL_POLARITY",
  "GOBP_POSITIVE_REGULATION_OF_MYOBLAST_DIFFERENTIATION",
  "GOBP_EPITHELIAL_CELL_PROLIFERATION",
  "GOBP_MESENCHYMAL_CELL_DEVELOPMENT", 
  #19 - ECM remodeling 
  "REACTOME_CELL_EXTRACELLULAR_MATRIX_INTERACTIONS",
  "REACTOME_CELL_EXTRACELLULAR_MATRIX_INTERACTIONS",
  "GOBP_REGULATION_OF_EXTRACELLULAR_MATRIX_DISASSEMBLY",
  "REACTOME_LAMININ_INTERACTIONS",
  "REACTOME_CROSSLINKING_OF_COLLAGEN_FIBRILS",
  "GOBP_ELASTIC_FIBER_ASSEMBLY",
  "REACTOME_DEGRADATION_OF_THE_EXTRACELLULAR_MATRIX",
  "REACTOME_COLLAGEN_FORMATION",
  "GOBP_COLLAGEN_FIBRIL_ORGANIZATION",
  "GOBP_CELL_MATRIX_ADHESION",
  "REACTOME_ELASTIC_FIBRE_FORMATION",
  "GOBP_SUPRAMOLECULAR_FIBER_ORGANIZATION",
  "REACTOME_COLLAGEN_CHAIN_TRIMERIZATION",
  "REACTOME_COLLAGEN_BIOSYNTHESIS_AND_MODIFYING_ENZYMES",
  "KEGG_ECM_RECEPTOR_INTERACTION",
  "REACTOME_NON_INTEGRIN_MEMBRANE_ECM_INTERACTIONS",
  "GOBP_EXTRACELLULAR_MATRIX_ASSEMBLY",
  "REACTOME_ECM_PROTEOGLYCANS",
  "REACTOME_EXTRACELLULAR_MATRIX_ORGANIZATION",
  #26 - Tissue morphogenesis 
  "GOBP_CELL_MORPHOGENESIS",
  "GOBP_CELLULAR_COMPONENT_MORPHOGENESIS",
  "GOBP_CELL_MORPHOGENESIS_INVOLVED_IN_DIFFERENTIATION",
  "GOBP_CELL_PART_MORPHOGENESIS",
  "GOBP_REGULATION_OF_DEVELOPMENTAL_GROWTH",
  "GOBP_POSITIVE_REGULATION_OF_ORGAN_GROWTH",
  "GOBP_REGULATION_OF_EXTENT_OF_CELL_GROWTH",
  "GOBP_REGULATION_OF_ANATOMICAL_STRUCTURE_MORPHOGENESIS",
  "GOBP_OUTFLOW_TRACT_MORPHOGENESIS",
  "GOBP_TISSUE_MORPHOGENESIS",
  "GOBP_MORPHOGENESIS_OF_A_POLARIZED_EPITHELIUM",
  "GOBP_TUBE_MORPHOGENESIS",
  "GOBP_MAMMARY_GLAND_FORMATION",
  "GOBP_EMBRYONIC_ORGAN_MORPHOGENESIS",
  "GOBP_BRANCHING_INVOLVED_IN_SALIVARY_GLAND_MORPHOGENESIS",
  "GOBP_MUSCLE_ORGAN_MORPHOGENESIS",
  "GOBP_CARDIAC_LEFT_VENTRICLE_MORPHOGENESIS",
  "GOBP_REGULATION_OF_BRANCHING_INVOLVED_IN_PROSTATE_GLAND_MORPHOGENESIS",
  "GOBP_ARTERY_MORPHOGENESIS",
  "GOBP_TRACHEA_MORPHOGENESIS",
  "GOBP_TISSUE_DEVELOPMENT",
  "GOBP_DEVELOPMENTAL_GROWTH_INVOLVED_IN_MORPHOGENESIS",
  "GOBP_ANIMAL_ORGAN_MORPHOGENESIS",
  "GOBP_PROSTATE_GLAND_MORPHOGENESIS",
  "GOBP_CARDIAC_NEURAL_CREST_CELL_MIGRATION_INVOLVED_IN_OUTFLOW_TRACT_MORPHOGENESIS",
  "GOBP_BLOOD_VESSEL_MORPHOGENESIS",
  #6 - Remodeling and wound healing 
  "GOBP_RESPONSE_TO_WOUNDING",
  "GOBP_NEGATIVE_REGULATION_OF_RESPONSE_TO_WOUNDING",
  "GOBP_REGULATION_OF_RESPONSE_TO_WOUNDING",
  "GOBP_WOUND_HEALING",
  "GOBP_ANGIOGENESIS_INVOLVED_IN_WOUND_HEALING",
  "GOBP_REGULATION_OF_BLOOD_VESSEL_REMODELING",
  #58 - Nervous system development
  "REACTOME_NEURONAL_SYSTEM",
  "GOBP_NEURON_PROJECTION_GUIDANCE",
  "REACTOME_NEUROTRANSMITTER_RECEPTORS_AND_POSTSYNAPTIC_SIGNAL_TRANSMISSION",
  "KEGG_AXON_GUIDANCE",
  "GOBP_CELL_MORPHOGENESIS_INVOLVED_IN_NEURON_DIFFERENTIATION",
  "GOBP_REGULATION_OF_NEURON_PROJECTION_DEVELOPMENT",
  "GOBP_POSITIVE_REGULATION_OF_AXON_EXTENSION",
  "GOBP_GLUTAMATE_RECEPTOR_SIGNALING_PATHWAY",
  "GOBP_CENTRAL_NERVOUS_SYSTEM_DEVELOPMENT",
  "GOBP_NEURAL_CREST_CELL_MIGRATION_INVOLVED_IN_AUTONOMIC_NERVOUS_SYSTEM_DEVELOPMENT",
  "GOBP_NERVOUS_SYSTEM_PROCESS",
  "GOBP_NEUROTRANSMITTER_BIOSYNTHETIC_PROCESS",
  "GOBP_POSITIVE_REGULATION_OF_NEURON_DIFFERENTIATION",
  "GOBP_DENDRITE_EXTENSION",
  "REACTOME_NEGATIVE_REGULATION_OF_NMDA_RECEPTOR_MEDIATED_NEURONAL_TRANSMISSION",
  "REACTOME_NEUROTRANSMITTER_RELEASE_CYCLE",
  "REACTOME_REGULATION_OF_COMMISSURAL_AXON_PATHFINDING_BY_SLIT_AND_ROBO",
  "GOBP_ANTERIOR_POSTERIOR_AXON_GUIDANCE",
  "GOBP_NEUROTRANSMITTER_TRANSPORT",
  "GOBP_NEURON_FATE_COMMITMENT",
  "GOBP_ENTERIC_NERVOUS_SYSTEM_DEVELOPMENT",
  "REACTOME_SEROTONIN_NEUROTRANSMITTER_RELEASE_CYCLE",
  "REACTOME_DOPAMINE_NEUROTRANSMITTER_RELEASE_CYCLE",
  "GOBP_AXONOGENESIS_INVOLVED_IN_INNERVATION",
  "GOBP_CHEMOREPULSION_OF_AXON",
  "GOBP_POSITIVE_REGULATION_OF_NEURON_PROJECTION_DEVELOPMENT",
  "GOBP_REGULATION_OF_NEURON_DIFFERENTIATION",
  "GOBP_NEUROTRANSMITTER_SECRETION",
  "GOBP_MOTOR_NEURON_AXON_GUIDANCE",
  "GOBP_AXONAL_FASCICULATION",
  "GOBP_POSITIVE_REGULATION_OF_AXONOGENESIS",
  "GOBP_PERIPHERAL_NERVOUS_SYSTEM_DEVELOPMENT",
  "GOBP_NEGATIVE_REGULATION_OF_AXON_EXTENSION",
  "GOBP_REGULATION_OF_NEURON_MIGRATION",
  "GOBP_NEUROPEPTIDE_SIGNALING_PATHWAY",
  "GOBP_NEGATIVE_REGULATION_OF_AXON_EXTENSION_INVOLVED_IN_AXON_GUIDANCE",
  "GOBP_AXONEME_ASSEMBLY",
  "GOBP_REGULATION_OF_NEUROTRANSMITTER_LEVELS",
  "GOBP_RESPONSE_TO_AXON_INJURY",
  "GOBP_CENTRAL_NERVOUS_SYSTEM_NEURON_DEVELOPMENT",
  "GOBP_FOREBRAIN_NEURON_DEVELOPMENT",
  "GOBP_NEURON_MIGRATION",
  "GOBP_NEGATIVE_REGULATION_OF_AXONOGENESIS",
  "GOBP_AXON_EXTENSION",
  "GOBP_NEURON_PROJECTION_EXTENSION_INVOLVED_IN_NEURON_PROJECTION_GUIDANCE",
  "GOBP_RETINAL_GANGLION_CELL_AXON_GUIDANCE",
  "GOBP_NEURON_DIFFERENTIATION",
  "GOBP_FOREBRAIN_GENERATION_OF_NEURONS",
  "GOBP_NEUROGENESIS",
  "GOBP_NEGATIVE_REGULATION_OF_NEURON_PROJECTION_DEVELOPMENT",
  "GOBP_NEURON_PROJECTION_EXTENSION",
  "GOBP_FOREBRAIN_NEURON_DIFFERENTIATION",
  "GOBP_REGULATION_OF_AXONOGENESIS",
  "GOBP_NEURON_CELL_CELL_ADHESION",
  "KEGG_NEUROACTIVE_LIGAND_RECEPTOR_INTERACTION",
  "GOBP_NEURON_DEVELOPMENT",
  "GOBP_AXON_DEVELOPMENT",
  "GOBP_CENTRAL_NERVOUS_SYSTEM_NEURON_DIFFERENTIATION",
  #7 - Musle contraction 
  "GOBP_REGULATION_OF_STRIATED_MUSCLE_CONTRACTION",
  "REACTOME_STRIATED_MUSCLE_CONTRACTION",
  "GOBP_STRIATED_MUSCLE_CONTRACTION",
  "GOBP_REGULATION_OF_CARDIAC_MUSCLE_CONTRACTION",
  "KEGG_VASCULAR_SMOOTH_MUSCLE_CONTRACTION",
  "REACTOME_MUSCLE_CONTRACTION",
  "GOBP_CARDIAC_CONDUCTION",
  #29 - Cellular interaction and synapse assembly 
  "GOBP_REGULATION_OF_SYNAPSE_STRUCTURE_OR_ACTIVITY",
  "GOBP_POSITIVE_REGULATION_OF_CELL_JUNCTION_ASSEMBLY",
  "GOBP_REGULATION_OF_HOMOTYPIC_CELL_CELL_ADHESION",
  "REACTOME_PROTEIN_PROTEIN_INTERACTIONS_AT_SYNAPSES",
  "REACTOME_TRANSMISSION_ACROSS_CHEMICAL_SYNAPSES",
  "GOBP_CELL_JUNCTION_ASSEMBLY",
  "GOBP_REGULATION_OF_CELL_JUNCTION_ASSEMBLY",
  "GOBP_REGULATION_OF_SYNAPSE_ASSEMBLY",
  "GOBP_BIOLOGICAL_ADHESION",
  "REACTOME_SYNAPTIC_ADHESION_LIKE_MOLECULES",
  "GOBP_CELL_CELL_ADHESION",
  "GOBP_POSITIVE_REGULATION_OF_SYNAPSE_ASSEMBLY",
  "GOBP_IMMUNOLOGICAL_SYNAPSE_FORMATION",
  "GOBP_SYNAPTIC_SIGNALING",
  "GOBP_SYNAPSE_ASSEMBLY",
  "GOBP_POSTSYNAPSE_ASSEMBLY",
  "GOBP_REGULATION_OF_SYNAPSE_STRUCTURAL_PLASTICITY",
  "GOBP_REGULATION_OF_EXCITATORY_SYNAPSE_ASSEMBLY",
  "GOBP_PROTEIN_LOCALIZATION_TO_SYNAPSE",
  "GOBP_RECEPTOR_LOCALIZATION_TO_SYNAPSE",
  "GOBP_EXCITATORY_SYNAPSE_ASSEMBLY",
  "REACTOME_CELL_CELL_COMMUNICATION",
  "GOBP_VESICLE_MEDIATED_TRANSPORT_IN_SYNAPSE",
  "GOBP_PROTEIN_LOCALIZATION_TO_POSTSYNAPSE",
  "GOBP_POSTSYNAPSE_ORGANIZATION",
  "GOBP_CELL_CELL_ADHESION_VIA_PLASMA_MEMBRANE_ADHESION_MOLECULES",
  "KEGG_FOCAL_ADHESION",
  "GOBP_SYNAPSE_ORGANIZATION",
  "GOBP_HOMOPHILIC_CELL_ADHESION_VIA_PLASMA_MEMBRANE_ADHESION_MOLECULES"
)

terms <- go_terms[go_terms$X %in% terms_oi,]
terms <-  terms[,c(1,6:9)]
rownames(terms) <- terms$X
terms$X <- NULL
terms_mtx <- as.matrix(terms)

terms_mtx <- terms_mtx[terms_oi,c(1,3,2,4)]

ComplexHeatmap::Heatmap(terms_mtx, name="z-score",
                        column_names_gp = grid::gpar(fontsize = 8),
                        row_names_gp = grid::gpar(fontsize = 2),
                        column_dend_height = unit(0.6, "cm"), row_dend_width = unit(0.85, "cm"),
                        column_names_rot = 45,cluster_rows = FALSE, cluster_columns = FALSE,column_title = "GO terms")

### Cellualr processes 
go_terms <- read.csv("/scratch/khandl/Neonatal_eosinophils/data_files/singleseqgset/singleseqgset_CO_SI_adult_and_neoP14_bonf.csv")

terms_oi <- c(#37 - Action potential and ion transport 
  "GOBP_REGULATION_OF_SODIUM_ION_TRANSPORT",
  "GOBP_REGULATION_OF_SODIUM_ION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_REGULATION_OF_MEMBRANE_POTENTIAL",
  "GOBP_ACTION_POTENTIAL",
  "GOBP_SODIUM_ION_TRANSPORT",
  "GOBP_REGULATION_OF_ACTION_POTENTIAL",
  "GOBP_ION_TRANSPORT",
  "GOBP_SODIUM_ION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_REGULATION_OF_ION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_ION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_MEMBRANE_DEPOLARIZATION_DURING_ACTION_POTENTIAL",
  "GOBP_NEGATIVE_REGULATION_OF_SODIUM_ION_TRANSPORT",
  "REACTOME_POTASSIUM_CHANNELS",
  "GOBP_NEGATIVE_REGULATION_OF_SODIUM_ION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_CARDIAC_MUSCLE_CELL_ACTION_POTENTIAL",
  "GOBP_CATION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_CATION_TRANSPORT",
  "GOBP_POSITIVE_REGULATION_OF_SODIUM_ION_TRANSPORT",
  "GOBP_POSITIVE_REGULATION_OF_ION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_REGULATION_OF_POSTSYNAPTIC_MEMBRANE_POTENTIAL",
  "GOBP_REGULATION_OF_CATION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_POSITIVE_REGULATION_OF_SODIUM_ION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_REGULATION_OF_SODIUM_PROTON_ANTIPORTER_ACTIVITY",
  "GOBP_NEGATIVE_REGULATION_OF_MEMBRANE_POTENTIAL",
  "GOBP_REGULATION_OF_PRESYNAPTIC_MEMBRANE_POTENTIAL",
  "GOBP_MEMBRANE_REPOLARIZATION",
  "GOBP_REGULATION_OF_LEUKOCYTE_DEGRANULATION",
  "GOBP_ATRIAL_CARDIAC_MUSCLE_CELL_MEMBRANE_REPOLARIZATION",
  "GOBP_NEGATIVE_REGULATION_OF_ION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_POTASSIUM_ION_TRANSPORT",
  "GOBP_CARDIAC_MUSCLE_CELL_ACTION_POTENTIAL_INVOLVED_IN_CONTRACTION",
  "GOBP_REGULATION_OF_CARDIAC_MUSCLE_CELL_ACTION_POTENTIAL",
  "REACTOME_VOLTAGE_GATED_POTASSIUM_CHANNELS",
  "GOBP_MEMBRANE_DEPOLARIZATION_DURING_CARDIAC_MUSCLE_CELL_ACTION_POTENTIAL",
  "GOBP_VENTRICULAR_CARDIAC_MUSCLE_CELL_ACTION_POTENTIAL",
  "REACTOME_PHASE_0_RAPID_DEPOLARISATION",
  "GOBP_REGULATION_OF_VENTRICULAR_CARDIAC_MUSCLE_CELL_ACTION_POTENTIAL", 
  #14 - Calcium influx 
  "GOBP_CALCIUM_ION_IMPORT",
  "GOBP_RESPONSE_TO_CALCIUM_ION",
  "GOBP_REGULATION_OF_CYTOSOLIC_CALCIUM_ION_CONCENTRATION",
  "GOBP_REGULATION_OF_RYANODINE_SENSITIVE_CALCIUM_RELEASE_CHANNEL_ACTIVITY",
  "GOBP_CALCIUM_ION_TRANSPORT",
  "GOBP_MONOCARBOXYLIC_ACID_TRANSPORT",
  "REACTOME_CA_DEPENDENT_EVENTS",
  "REACTOME_SODIUM_CALCIUM_EXCHANGERS",
  "GOBP_DETECTION_OF_CALCIUM_ION",
  "REACTOME_REDUCTION_OF_CYTOSOLIC_CA_LEVELS",
  "GOBP_CALCIUM_ION_TRANSMEMBRANE_TRANSPORT",
  "KEGG_CALCIUM_SIGNALING_PATHWAY",
  "GOBP_CALCIUM_DEPENDENT_CELL_CELL_ADHESION_VIA_PLASMA_MEMBRANE_CELL_ADHESION_MOLECULES",
  "GOBP_POSITIVE_REGULATION_OF_MITOCHONDRIAL_CALCIUM_ION_CONCENTRATION",
  #7 - ROS and RNS generation 
  "GOBP_NITRIC_OXIDE_MEDIATED_SIGNAL_TRANSDUCTION",
  "GOBP_REGULATION_OF_NITRIC_OXIDE_MEDIATED_SIGNAL_TRANSDUCTION",
  "GOBP_RESPONSE_TO_OXYGEN_RADICAL",
  "GOBP_POSITIVE_REGULATION_OF_NITRIC_OXIDE_MEDIATED_SIGNAL_TRANSDUCTION",
  "GOBP_REGULATION_OF_SUPEROXIDE_METABOLIC_PROCESS",
  "GOBP_SUPEROXIDE_ANION_GENERATION",
  "GOBP_SUPEROXIDE_METABOLIC_PROCESS",
  #3 - Metabolism 
  "REACTOME_PP2A_MEDIATED_DEPHOSPHORYLATION_OF_KEY_METABOLIC_FACTORS",
  "GOBP_POSITIVE_REGULATION_OF_NUCLEOTIDE_METABOLIC_PROCESS",
  "GOBP_POSITIVE_REGULATION_OF_ATP_METABOLIC_PROCESS",
  #3 - Eicosanoid synthesis 
  "REACTOME_EICOSANOIDS",
  "REACTOME_SYNTHESIS_OF_5_EICOSATETRAENOIC_ACIDS",
  "GOBP_LIPOXYGENASE_PATHWAY",
  #7 - Membrane dynamics 
  "GOBP_POSITIVE_REGULATION_OF_PHOSPHOLIPID_TRANSLOCATION",
  "GOBP_NEGATIVE_REGULATION_OF_LIPID_STORAGE",
  "GOBP_AMINOPHOSPHOLIPID_TRANSLOCATION",
  "GOBP_REGULATION_OF_PHOSPHOLIPID_TRANSLOCATION",
  "GOBP_AMINOPHOSPHOLIPID_TRANSPORT",
  "GOBP_REGULATION_OF_MEMBRANE_LIPID_DISTRIBUTION",
  "GOBP_LIPID_TRANSLOCATION",
  #9 - Chemotaxis 
  "GOBP_NEGATIVE_CHEMOTAXIS",
  "GOBP_NEGATIVE_REGULATION_OF_CHEMOTAXIS",
  "GOBP_POSITIVE_REGULATION_OF_CHEMOTAXIS",
  "GOBP_REGULATION_OF_POSITIVE_CHEMOTAXIS",
  "GOBP_POSITIVE_CHEMOTAXIS",
  "GOBP_REGULATION_OF_NEUTROPHIL_CHEMOTAXIS",
  "GOBP_REGULATION_OF_CHEMOTAXIS",
  "GOBP_POSITIVE_REGULATION_OF_MACROPHAGE_CHEMOTAXIS",
  "GOBP_REGULATION_OF_GRANULOCYTE_CHEMOTAXIS",
  #21 - Reorganisation of cytoskeleton 
  "GOBP_CORTICAL_CYTOSKELETON_ORGANIZATION",
  "GOBP_CYTOSKELETON_ORGANIZATION",
  "GOBP_ACTIN_FILAMENT_BASED_TRANSPORT",
  "GOBP_POSITIVE_REGULATION_OF_ACTIN_NUCLEATION",
  "GOBP_ACTIN_POLYMERIZATION_DEPENDENT_CELL_MOTILITY",
  "GOBP_ARP2_3_COMPLEX_MEDIATED_ACTIN_NUCLEATION",
  "GOBP_ACTIN_FILAMENT_BUNDLE_ORGANIZATION",
  "GOBP_ACTIN_CYTOSKELETON_REORGANIZATION",
  "GOBP_ACTIN_NUCLEATION",
  "GOBP_POSITIVE_REGULATION_OF_ARP2_3_COMPLEX_MEDIATED_ACTIN_NUCLEATION",
  "GOBP_ACTIN_FILAMENT_SEVERING",
  "GOBP_ACTIN_POLYMERIZATION_OR_DEPOLYMERIZATION",
  "GOBP_REGULATION_OF_ACTIN_FILAMENT_BASED_MOVEMENT",
  "GOBP_ACTIN_FILAMENT_POLYMERIZATION",
  "GOBP_REGULATION_OF_ACTIN_FILAMENT_ORGANIZATION",
  "GOBP_NEGATIVE_REGULATION_OF_ACTIN_FILAMENT_POLYMERIZATION",
  "GOBP_REGULATION_OF_ACTIN_FILAMENT_LENGTH",
  "GOBP_ACTIN_MEDIATED_CELL_CONTRACTION",
  "GOBP_REGULATION_OF_ACTIN_FILAMENT_BASED_PROCESS",
  "KEGG_REGULATION_OF_ACTIN_CYTOSKELETON",
  "GOBP_ACTIN_FILAMENT_BASED_PROCESS",
  #4 - Cell growth 
  "GOBP_POSITIVE_REGULATION_OF_DEVELOPMENTAL_GROWTH",
  "GOBP_REGULATION_OF_CELL_DEVELOPMENT",
  "GOBP_REGULATION_OF_CELL_SIZE",
  "GOBP_DEVELOPMENTAL_CELL_GROWTH"
)

terms <- go_terms[go_terms$X %in% terms_oi,]
terms <-  terms[,c(1,6:9)]
rownames(terms) <- terms$X
terms$X <- NULL
terms_mtx <- as.matrix(terms)

terms_mtx <- terms_mtx[terms_oi,c(1,3,2,4)]

ComplexHeatmap::Heatmap(terms_mtx, name="z-score",
                        column_names_gp = grid::gpar(fontsize = 8),
                        row_names_gp = grid::gpar(fontsize = 2),
                        column_dend_height = unit(0.6, "cm"), row_dend_width = unit(0.85, "cm"),
                        column_names_rot = 45,cluster_rows = FALSE, cluster_columns = FALSE,column_title = "GO terms")

### Activated pathways 
go_terms <- read.csv("/scratch/khandl/Neonatal_eosinophils/data_files/singleseqgset/singleseqgset_CO_SI_adult_and_neoP14_bonf.csv")

terms_oi <- c(#2 - Mapk signaling 
  "REACTOME_NEGATIVE_FEEDBACK_REGULATION_OF_MAPK_PATHWAY",
  "KEGG_MAPK_SIGNALING_PATHWAY", 
  #3 - Wnt signaling 
  "GOBP_REGULATION_OF_CANONICAL_WNT_SIGNALING_PATHWAY",
  "GOBP_POSITIVE_REGULATION_OF_CANONICAL_WNT_SIGNALING_PATHWAY",
  "GOBP_REGULATION_OF_WNT_SIGNALING_PATHWAY",
  #1 - FcyR signaling 
  "KEGG_FC_GAMMA_R_MEDIATED_PHAGOCYTOSIS",
  #2 - TGFb signaling 
  "GOBP_TRANSFORMING_GROWTH_FACTOR_BETA_PRODUCTION",
  "KEGG_TGF_BETA_SIGNALING_PATHWAY",
  #3 - LPS and Peptidoglycan signaling 
  "GOBP_LIPOPOLYSACCHARIDE_MEDIATED_SIGNALING_PATHWAY",
  "GOBP_POSITIVE_REGULATION_OF_LIPOPOLYSACCHARIDE_MEDIATED_SIGNALING_PATHWAY",
  "GOBP_RESPONSE_TO_PEPTIDOGLYCAN"
)

terms <- go_terms[go_terms$X %in% terms_oi,]
terms <-  terms[,c(1,6:9)]
rownames(terms) <- terms$X
terms$X <- NULL
terms_mtx <- as.matrix(terms)

terms_mtx <- terms_mtx[terms_oi,c(1,3,2,4)]

ComplexHeatmap::Heatmap(terms_mtx, name="z-score",
                        column_names_gp = grid::gpar(fontsize = 8),
                        row_names_gp = grid::gpar(fontsize = 2),
                        column_dend_height = unit(0.6, "cm"), row_dend_width = unit(0.85, "cm"),
                        column_names_rot = 45,cluster_rows = FALSE, cluster_columns = FALSE,column_title = "GO terms")

